### ISSUE TITLE
How to set custom name for the artifact

### ISSUE THREAD

**Issue by AdnanTheEntertainer** [sky-uk/gradle-maven-plugin#27]
How to set **custom name attribute** for the artifact:

**1. Group
2. Name
3. Version**

as mentioned in your example 
 **dependencyNode.appendNode('groupId', dep.group)
    dependencyNode.appendNode('artifactId', dep.name)
    dependencyNode.appendNode('version', dep.version)**

as above are not accessible in your case and also there is no global variable defined for this:

project.ext {
    mavDevelopers = ["Fe":"Federico"]
    mavSiteUrl = "https://github.com/sky-uk/gradle-maven-plugin"
    mavGitUrl = mavSiteUrl + '.git'
    mavProjectName = 'GradleMavenizer'
    mavPublishToInternalRepo = true
    mavRepoInternalUrl = "path/to/internal/repo"
    mavLibraryLicenses = ["Apache-2.0":'http://www.apache.org/licenses/LICENSE-2.0.txt']
    mavLibraryDescription = "A simple description of the project"
}

**Comment by Fed93** [comment]
@AdnanTheEntertainer i can't understand the problem.
You are considering the piece of code related to the dependencies declared in the project.
When you create a Java/Android Library you have to declare 
```
group = library_project_group
version = library_version
```
in your library `build.gradle` file.
These properties will be automatically added to the pom file.
Finally the default artifact name is the name of the library you inserted during the creation of the project.

**Comment by Buli1212** [comment]
@Fed93 The problem is being unable to specify the artifactId in the configuration. By default the folder name of the project is used. 
The workaround is to put rootProject.name = "yourartifactname" in settings.gradle file but if your library is using modules that's not gonna work and you can end up uploading an artifact called "app".

implementation '<group>:<name>:<version>'
all 3 parameters should be configurable

Without your plugin it would be done this way:
    publications {
        maven(MavenPublication) {

            groupId 'com.yourgroup'
            artifactId 'yourartifact'
            version android.defaultConfig.versionName
      }
}

**Comment by gotev** [comment]
Check this project which is using this plugin and has multiple modules: https://github.com/gotev/android-upload-service
